import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  en: {
    tagline: "A quieter kind of care",
    heroTitle1: "Memory is a",
    heroTitle2: "place we can return to.",
    heroDesc: "AI helps families and care teams make everyday moments feel familiar, supported, and human.",
    regionNote: "Built for thoughtful care in the North Eastern region of India.",
    privateBadge: "Private by design",
    welcomeBack: "Welcome back",
    beginSpace: "Begin your care space",
    seeYouAgain: "Good to see you",
    togetherTitle: "A little more",
    togetherEm: "together.",
    loginSubtitle: "Sign in to continue to your memory care space.",
    signupSubtitle: "Create a private space for your family and care team.",
    signInTab: "Sign in",
    createAccountTab: "Create account",
    continueAs: "Continue as",
    createAs: "Create your account as",
    rolePatient: "Patient",
    rolePatientSub: "Elderly user",
    roleCaregiver: "Caregiver",
    roleCaregiverSub: "Family member",
    roleClinician: "Healthcare worker",
    roleClinicianSub: "Authorized professional",
    emailLabel: "Email address",
    nameLabel: "Your name",
    passwordLabel: "Password",
    forgotPass: "Forgot password?",
    emailPlaceholder: "you@example.com",
    namePlaceholder: "Priya Devi",
    passPlaceholder: "At least 6 characters",
    termsText: "I agree to the thoughtful care terms and understand this is a support tool, not a medical diagnosis.",
    loginBtn: "Continue to AI",
    signupBtn: "Create my care space",
    demoBtn: "Explore the demo without signing in",
    privacyFooter: "Your information stays yours. AI uses clear language and explainable observations to support care conversations.",
    copyright: "© 2026 AI Memory Care",
    footerLinks: "Help · Privacy · Accessibility",
    verifyTitle: "Verify your identity",
    verifyHeader: "Secure your",
    verifyHeaderEm: "account.",
    verifySub: "Please enter the 6-digit OTP sent to",
    verifyBtn: "Verify OTP",
    resendText: "Didn't receive a code?",
    resendBtn: "Resend OTP",
    verifying: "Verifying...",
    creating: "Creating your space...",
    authenticating: "Authenticating...",
    patientProfile: "Patient Profile",
    managePrefs: "Manage your personal details and application preferences.",
    logout: "Log Out",
    saveChanges: "Save Changes",
    profilePhoto: "Profile Photo",
    imageConstraint: "JPG or PNG, max 2MB",
    fullName: "Full Name",
    dob: "Date of Birth",
    location: "Location",
    emergencyContact: "Emergency Contact",
    memoryVaultTitle: "The memory vault",
    memoryVaultSub: "A life, remembered in many ways.",
    addMemoryBtn: "Add a memory",
    aiCompanionTitle: "AI companion",
    aiCompanionSub: "A calm voice, whenever you need it.",
    talkCompanion: "Talk with your companion",
    companionSubText: "I'm here to listen.",
    seeWhatsNext: "See what's next",
    calmPlan: "Your calm plan for today.",
    todaysMoments: "Today’s moments",
    beginTogether: "Begin together",
    watchReels: "Watch Daily Reels",
    howFeeling: "How are you feeling?",
    feelingSub: "Your day can be taken one moment at a time.",
    littleWindows: "Little windows into your life",
    openVault: "Open memory vault",
    exit: "Exit",
    previous: "Previous",
    nextMoment: "Next moment",
    todaysLastMoment: "Today’s last moment",
    thatsAll: "That’s all for today.",
    exploreMoments: "You’ve explored today’s moments. Come back whenever you like.",
    backHome: "Back home",
    goodMorning: "Good morning",
    goodEvening: "Good evening",
    goodAfternoon: "Good afternoon",
    interfaceLanguage: "Interface Language",
    activePatient: "Active Patient",
    selectContext: "Select context to load records",
    todayOverview: "Today",
    gentleCheckIn: "A gentle check-in.",
    recentActivity: "Recent activity",
    smallStory: "A small story of the day.",
    over14Days: "Over the last 14 days",
    usefulPatterns: "A few useful patterns.",
    viewFullProgress: "View full progress",
    thoughtfulObservation: "A thoughtful observation",
    recentMemoriesHeader: "Recent memories",
    momentsConnect: "The moments that connect.",
    nextUpHeader: "Next up",
    manageAllReminders: "Manage all reminders",
    oneThoughtfulStep: "One thoughtful next step",
    addMemoryCardTitle: "Add a memory from home",
    cognitiveProgressTitle: "Cognitive Progress",
    interactiveTracking: "Interactive 7-day tracking for accuracy and response times.",
    memoryActivity: "Memory Activity",
    responseTime: "Response Time",
    noteOnTracking: "A note on tracking",
    scheduleNewTask: "Schedule New Task",
    taskName: "Task Name",
    dateTime: "Date & Time",
    instructions: "Instructions",
    addToSchedule: "Add to Schedule",
    allScheduledReminders: "All Scheduled Reminders",
    simulateFamilyMsg: "Simulate Family Message",
    simulateSub: "For demo purposes: simulate a message arriving from a family member's app.",
    sender: "Sender",
    messageLabel: "Message",
    sendBtn: "Send",
    familyHubFeed: "Family Hub Feed",
    readAloud: "Read Aloud",
    caregiverClinicalNotes: "Caregiver Clinical Notes",
    saveNote: "Save Note",
    patientPreferences: "Patient Preferences",
    pushNotifications: "Push Notifications",
    highContrastMode: "High Contrast Mode",
    memoryConstellation: "Memory Constellation",
    caregiverProfile: "Caregiver Profile",
    caregiverPrefs: "Manage your personal details and app preferences."
  },
  as: { // Assamese (অসমীয়া)
    tagline: "এখনি শান্ত যতন",
    heroTitle1: "স্মৃতি হৈছে",
    heroTitle2: "যি স্থানলৈ আমি উভতি যাব পাৰোঁ।",
    heroDesc: "এআই-য়ে পৰিয়াল আৰু যতনকাৰীসকলক দৈনন্দিন ক্ষণবোৰ আপোন কৰি তোলাত সহায় কৰে।",
    regionNote: "ভাৰতৰ উত্তৰ-পূব অঞ্চলৰ যতনৰ বাবে নিৰ্মিত।",
    privateBadge: "নিৰাপদ আৰু গোপনীয়",
    welcomeBack: "পুনৰ স্বাগতম",
    beginSpace: "আপোনাৰ যতনৰ স্থান আৰম্ভ কৰক",
    seeYouAgain: "আপোনাক পুনৰ দেখা পাই",
    togetherTitle: "আৰু অলপ",
    togetherEm: "একেলগে।",
    loginSubtitle: "আপোনাৰ স্মৃতি যতন স্থানলৈ ছাইন ইন কৰক।",
    signupSubtitle: "আপোনাৰ পৰিয়ালৰ বাবে এটি গোপনীয় স্থান সৃষ্টি কৰক।",
    signInTab: "ছাইন ইন",
    createAccountTab: "একাউণ্ট সৃষ্টি কৰক",
    continueAs: "হিচাপে অব্যাহত ৰাখক",
    createAs: "হিচাপে একাউণ্ট সৃষ্টি কৰক",
    rolePatient: "ৰোগী",
    rolePatientSub: "বয়োজ্যেষ্ঠ ব্যৱহাৰকাৰী",
    roleCaregiver: "যতনকাৰী",
    roleCaregiverSub: "পৰিয়ালৰ সদস্য",
    roleClinician: "স্বাস্থ্যকৰ্মী",
    roleClinicianSub: "অভিজ্ঞ পেছাদাৰী",
    emailLabel: "ইমেইল ঠিকনা",
    nameLabel: "আপোনাৰ নাম",
    passwordLabel: "পাছৱৰ্ড",
    forgotPass: "পাছৱৰ্ড পাহৰিলে?",
    emailPlaceholder: "you@example.com",
    namePlaceholder: "প্ৰিয়া দেৱী",
    passPlaceholder: "ককমপক্ষে ৬ টা আখৰ",
    termsText: "মই যতনৰ চৰ্তাৱলী মানি লৈছোঁ আৰু বুজি পাইছোঁ যে এইটো চিকিৎসা নিৰ্ণয় নহয়।",
    loginBtn: "এআই লৈ যাওক",
    signupBtn: "মোৰ যতনৰ স্থান সৃষ্টি কৰক",
    demoBtn: "ছাইন ইন নকৰাকৈ ডেমো চাওক",
    privacyFooter: "আপোনাৰ তথ্য সুৰক্ষিত। এআই-য়ে সঠিক পৰামৰ্শ দিয়ে।",
    copyright: "© ২০২৬ এআই মেম’ৰী কেয়াৰ",
    footerLinks: "সহায় · গোপনীয়তা · সুলভতা",
    verifyTitle: "প্ৰমাণীকৰণ কৰক",
    verifyHeader: "আপোনাৰ একাউণ্ট",
    verifyHeaderEm: "সুৰক্ষিত কৰক।",
    verifySub: "অনুগ্ৰহ কৰি প্ৰেৰণ কৰা ওটিপি উল্লেখ কৰক",
    verifyBtn: "ওটিপি পৰীক্ষা কৰক",
    resendText: "কোড পোৱা নাই?",
    resendBtn: "পুনৰ ওটিপি পঠাওক",
    verifying: "পৰীক্ষা কৰা হৈছে...",
    creating: "স্থান সৃষ্টি কৰা হৈছে...",
    authenticating: "প্ৰমাণীকৰণ হৈছে...",
    patientProfile: "ৰোগীৰ প্ৰফাইল",
    managePrefs: "আপোনাৰ ব্যক্তিগত বিৱৰণ আৰু পছন্দসমূহ পৰিচালনা কৰক।",
    logout: "লগ আউট",
    saveChanges: "সলনিসমূহ সংৰক্ষণ কৰক",
    profilePhoto: "প্ৰফাইল ফটো",
    imageConstraint: "JPG বা PNG, সৰ্বোচ্চ ২ MB",
    fullName: "সম্পূৰ্ণ নাম",
    dob: "জন্ম তাৰিখ",
    location: "অঞ্চল",
    emergencyContact: "জৰুৰীকালীন যোগাযোগ",
    memoryVaultTitle: "স্মৃতিৰ ভঁৰাল",
    memoryVaultSub: "বিভিন্ন ধৰণে স্মৰণ কৰা এটা জীৱন।",
    addMemoryBtn: "স্মৃতি যোগ কৰক",
    aiCompanionTitle: "এআই সংগী",
    aiCompanionSub: "আপোনাৰ প্ৰয়োজন হোৱাৰ সময়ত এটি শান্ত কণ্ঠ।",
    talkCompanion: "আপোনাৰ সংগীৰ সৈতে কথা পাতক",
    companionSubText: "মই শুনিবলৈ ইয়াত আছোঁ।",
    seeWhatsNext: "পৰৱৰ্তী কি আছে চাওক",
    calmPlan: "বৰ্তমানৰ বাবে আপোনাৰ শান্ত পৰিকল্পনা।",
    todaysMoments: "আজীৱন ক্ষণসমূহ",
    beginTogether: "একেলগে আৰম্ভ কৰক",
    watchReels: "দৈনন্দিন ৰীলসমূহ চাওক",
    howFeeling: "আপোনাৰ কেমন অনুভৱ হৈছে?",
    feelingSub: "প্ৰতিটো ক্ষণ সাৱধানে উপভোগ কৰক।",
    littleWindows: "আপোনাৰ জীৱনৰ সৰু সৰু খিৰিকীসমূহ",
    openVault: "স্মৃতিৰ ভঁৰাল খোলক",
    exit: "ওলাই যাওক",
    previous: "পূৰ্বৰ",
    nextMoment: "পৰৱৰ্তী ক্ষণ",
    todaysLastMoment: "আজিৰ শেষ ক্ষণ",
    thatsAll: "আজিৰ বাবে ইমানেই।",
    exploreMoments: "আপুনি আজিৰ ক্ষণসমূহ চাই শেষ কৰিলে।",
    backHome: "ঘৰলৈ উভতি যাওক",
    goodMorning: "শুভ প্ৰভাত",
    goodEvening: "শুভ সন্ধ্যা",
    goodAfternoon: "শুভ দুপৰীয়া",
    interfaceLanguage: "ইণ্টাৰফেচ ভাষা",
    activePatient: "সক্ৰিয় ৰোগী",
    selectContext: "অভিলেখ ল’ড কৰিবলৈ প্ৰসংগ বাছনি কৰক",
    todayOverview: "আজি",
    gentleCheckIn: "এক শান্ত পৰীক্ষা।",
    recentActivity: "শেহতীয়া কাৰ্যকলাপ",
    smallStory: "দিনটোৰ এটা সৰু কাহিনী।",
    over14Days: "যোৱা ১৪ দিনত",
    usefulPatterns: "কেতবোৰ উপযোগী আৰ্হি।",
    viewFullProgress: "সম্পূৰ্ণ অগ্ৰগতি চাওক",
    thoughtfulObservation: "এটি চিন্তাশীল পৰ্যবেক্ষণ",
    recentMemoriesHeader: "শেহতীয়া স্মৃতিসমূহ",
    momentsConnect: "যি ক্ষণসমূহে সংযুক্ত কৰে।",
    nextUpHeader: "পৰৱৰ্তী",
    manageAllReminders: "সকলো সোঁৱৰণী পৰিচালনা কৰক",
    oneThoughtfulStep: "এটি চিন্তাশীল পৰৱৰ্তী পদক্ষেপ",
    addMemoryCardTitle: "ঘৰৰ পৰা এটা স্মৃতি যোগ কৰক",
    cognitiveProgressTitle: "জ্ঞানমূলক অগ্ৰগতি",
    interactiveTracking: "শুদ্ধতা আৰু প্ৰতিক্ৰিয়া সময়ৰ বাবে ৭ দিনীয়া ট্ৰেকিং।",
    memoryActivity: "স্মৃতি কাৰ্যকলাপ",
    responseTime: "প্ৰতিক্ৰিয়া সময়",
    noteOnTracking: "ট্ৰেকিঙৰ বিষয়ে এটা টোকা",
    scheduleNewTask: "নতুন কাম সূচীভুক্ত কৰক",
    taskName: "কামৰ নাম",
    dateTime: "তাৰিখ আৰু সময়",
    instructions: "নিৰ্দেশনাসমূহ",
    addToSchedule: "সূচীলৈ যোগ কৰক",
    allScheduledReminders: "সূচীভুক্ত সকলো সোঁৱৰণী",
    simulateFamilyMsg: "পৰিয়ালৰ বাৰ্তা চিমুলেট কৰক",
    simulateSub: "ডেমো উদ্দেশ্যৰ বাবে।",
    sender: "প্ৰেৰক",
    messageLabel: "বাৰ্তা",
    sendBtn: "প্ৰেৰণ কৰক",
    familyHubFeed: "পৰিয়াল হাব ফিড",
    readAloud: "উচ্চস্বৰে পঢ়ক",
    caregiverClinicalNotes: "যতনকাৰীৰ ক্লিিনকেল টোকাসমূহ",
    saveNote: "টোকা সংৰক্ষণ কৰক",
    patientPreferences: "ৰোগীৰ পছন্দসমূহ",
    pushNotifications: "পুশ জাননীসমূহ",
    highContrastMode: "উচ্চ কনট্ৰাষ্ট ম’ড",
    memoryConstellation: "স্মৃতি নক্ষত্রমণ্ডল",
    caregiverProfile: "যতনকাৰীৰ প্ৰফাইল",
    caregiverPrefs: "আপোনাৰ ব্যক্তিগত বিৱৰণ পৰিচালনা কৰক।"
  },
  bn: { // Bengali (বাংলা)
    tagline: "শান্তিপূর্ণ সেবা",
    heroTitle1: "স্মৃতি হলো",
    heroTitle2: "যেখানে আমরা ফিরে যেতে পারি।",
    heroDesc: "এআই পরিবার এবং সেবাকারীদের দৈনন্দিন মুহূর্তগুলোকে পরিচিত ও নিরাপদ করতে সাহায্য করে।",
    regionNote: "ভারতের উত্তর-পূর্বাঞ্চলের সেবার জন্য তৈরি।",
    privateBadge: "গোপনীয় ও নিরাপদ",
    welcomeBack: "স্বাগতম",
    beginSpace: "আপনার সেবার স্থান শুরু করুন",
    seeYouAgain: "আপনাকে আবার দেখে",
    togetherTitle: "আরেকটু",
    togetherEm: "একসাথে।",
    loginSubtitle: "আপনার স্মৃতি সেবা স্থানে সাইন ইন করুন।",
    signupSubtitle: "আপনার পরিবারের জন্য একটি গোপন স্থান তৈরি করুন।",
    signInTab: "সাইন ইন",
    createAccountTab: "অ্যাকাউন্ট তৈরি করুন",
    continueAs: "হিসাবে চালিয়ে যান",
    createAs: "হিসাবে অ্যাকাউন্ট তৈরি করুন",
    rolePatient: "রোগী",
    rolePatientSub: "বয়স্ক ব্যবহারকারী",
    roleCaregiver: "সেবাকারী",
    roleCaregiverSub: "পরিবারের সদস্য",
    roleClinician: "স্বাস্থ্যকর্মী",
    roleClinicianSub: "পেশাদার বিশেষজ্ঞ",
    emailLabel: "ইমেল ঠিকানা",
    nameLabel: "আপনার নাম",
    passwordLabel: "পাসওয়ার্ড",
    forgotPass: "পাসওয়ার্ড ভুলে গেছেন?",
    emailPlaceholder: "you@example.com",
    namePlaceholder: "প্রিয়া দেবী",
    passPlaceholder: "কমপক্ষে ৬ অক্ষর",
    termsText: "আমি সেবার শর্তাবলীতে সম্মত এবং এটি কোনো চিকিৎসা নির্ণয় নয় তা বুঝি।",
    loginBtn: "এআই তে যান",
    signupBtn: "আমার সেবার স্থান তৈরি করুন",
    demoBtn: "সাইন ইন ছাড়া ডেমো দেখুন",
    privacyFooter: "আপনার তথ্য সুরক্ষিত থাকে।",
    copyright: "© ২০২৬ এআই মেমোরি কেয়ার",
    footerLinks: "সাহায্য · গোপনীয়তা",
    verifyTitle: "পরিচয় যাচাই করুন",
    verifyHeader: "আপনার অ্যাকাউন্ট",
    verifyHeaderEm: "সুরক্ষিত করুন।",
    verifySub: "প্রেরিত ওটিপি লিখুন",
    verifyBtn: "ওটিপি যাচাই করুন",
    resendText: "কোড পাননি?",
    resendBtn: "পুনরায় ওটিপি পাঠান",
    verifying: "যাচাই করা হচ্ছে...",
    creating: "তৈরি করা হচ্ছে...",
    authenticating: "প্রমাণীকরণ হচ্ছে...",
    patientProfile: "রোগীর প্রফাইল",
    managePrefs: "আপনার ব্যক্তিগত বিবরণ পরিচালনা করুন।",
    logout: "লগ আউট",
    saveChanges: "পরিবর্তন সংরক্ষণ করুন",
    profilePhoto: "প্রফাইল ছবি",
    imageConstraint: "JPG বা PNG, সর্বোচ্চ ২MB",
    fullName: "সম্পূর্ণ নাম",
    dob: "জন্ম তারিখ",
    location: "অবস্থান",
    emergencyContact: "জরুরী যোগাযোগ",
    memoryVaultTitle: "স্মৃতির ভাণ্ডার",
    memoryVaultSub: "একটি জীবন, বিভিন্নভাবে স্মরণীয়।",
    addMemoryBtn: "স্মৃতি যোগ করুন",
    aiCompanionTitle: "এআই সহচর",
    aiCompanionSub: "প্রয়োজনের সময় একটি শান্ত কণ্ঠস্বর।",
    talkCompanion: "সহচরের সাথে কথা বলুন",
    companionSubText: "আমি শোনার জন্য আছি।",
    seeWhatsNext: "সামনে কী আছে দেখুন",
    calmPlan: "আজকের আপনার শান্ত পরিকল্পনা।",
    todaysMoments: "আজকের মুহূর্তগুলি",
    beginTogether: "একসাথে শুরু করুন",
    watchReels: "দৈনিক রিল দেখুন",
    howFeeling: "আপনার কেমন লাগছে?",
    feelingSub: "প্রতিটি মুহূর্ত শান্তিতে উপভোগ করুন।",
    littleWindows: "আপনার জীবনের ছোট জানালা",
    openVault: "স্মৃতির ভাণ্ডার খুলুন",
    exit: "প্রস্থান",
    previous: "পূর্ববর্তী",
    nextMoment: "পরবর্তী মুহূর্ত",
    todaysLastMoment: "আজকের শেষ মুহূর্ত",
    thatsAll: "আজকের মতো এইটুকুই।",
    exploreMoments: "আপনি আজকের মুহূর্তগুলি দেখেছেন।",
    backHome: "ফিরে যান",
    goodMorning: "সুপ্রভাত",
    goodEvening: "শুভ সন্ধ্যা",
    goodAfternoon: "শুভ দুপুর",
    interfaceLanguage: "ইন্টারফেস ভাষা",
    activePatient: "সক্রিয় রোগী",
    selectContext: "রেকর্ড লোড করতে পটভূমি নির্বাচন করুন",
    todayOverview: "আজ",
    gentleCheckIn: "একটি মৃদু চেক-ইন।",
    recentActivity: "সাম্প্রতিক কার্যকলাপ",
    smallStory: "দিনের একটি ছোট গল্প।",
    over14Days: "গত ১৪ দিনে",
    usefulPatterns: "কিছু দরকারী প্যাটার্ন।",
    viewFullProgress: "সম্পূর্ণ অগ্রগতি দেখুন",
    thoughtfulObservation: "একটি চিন্তাশীল পর্যবেক্ষণ",
    recentMemoriesHeader: "সাম্প্রতিক স্মৃতি",
    momentsConnect: "যে মুহূর্তগুলি সংযুক্ত করে।",
    nextUpHeader: "সামনে আসছে",
    manageAllReminders: "সমস্ত রিমিন্ডার পরিচালনা করুন",
    oneThoughtfulStep: "একটি চিন্তাশীল পরবর্তী পদক্ষেপ",
    addMemoryCardTitle: "বাড়ি থেকে একটি স্মৃতি যোগ করুন",
    cognitiveProgressTitle: "জ্ঞানীয় অগ্রগতি",
    interactiveTracking: "নির্ভুলতা এবং প্রতিক্রিয়ার সময়ের জন্য ৭ দিনের ট্র্যাকিং।",
    memoryActivity: "স্মৃতি কার্যকলাপ",
    responseTime: "প্রতিক্রিয়া সময়",
    noteOnTracking: "ট্র্যাকিং সম্পর্কিত একটি নোট",
    scheduleNewTask: "নতুন কাজ সময়সূচী করুন",
    taskName: "কাজের নাম",
    dateTime: "তারিখ ও সময়",
    instructions: "নির্দেশাবলী",
    addToSchedule: "সময়সূচীতে যোগ করুন",
    allScheduledReminders: "সমস্ত নির্ধারিত রিমিন্ডার",
    simulateFamilyMsg: "পারিবারিক বার্তা অনুকরণ করুন",
    simulateSub: "ডেমো উদ্দেশ্যে।",
    sender: "প্রকের",
    messageLabel: "বার্তা",
    sendBtn: "পাঠান",
    familyHubFeed: "ফ্যামিলি হাব ফিড",
    readAloud: "জোরে পড়ুন",
    caregiverClinicalNotes: "সেবাকারীর ক্লিনিক্যাল নোট",
    saveNote: "নোট সংরক্ষণ করুন",
    patientPreferences: "রোগীর পছন্দ",
    pushNotifications: "পুশ বিজ্ঞপ্তি",
    highContrastMode: "হাই কন্ট্রাস্ট মোড",
    memoryConstellation: "স্মৃতি নক্ষত্রমণ্ডল",
    caregiverProfile: "সেবাকারীর প্রফাইল",
    caregiverPrefs: "আপনার ব্যক্তিগত বিবরণ পরিচালনা করুন।"
  },
  mni: { // Meitei (Manipuri - মৈতৈলোন্)
    tagline: "অঙনবগী য়ুমথৈ",
    heroTitle1: "নিংশিংবা অসি",
    heroTitle2: "হলকপা য়াংবা মফম অমনি।",
    heroDesc: "এআইনা ইমুং মনুংবু মতেং পাংই।",
    regionNote: "ভারতকী নোংচুপ থংবা লমদমগীদমক শাবা।",
    privateBadge: "নঙগী থাজবা মফম",
    welcomeBack: "করম্লবা",
    beginSpace: "হৌদোকপীয়ু",
    seeYouAgain: "উবদা হরাওবা",
    togetherTitle: "হেন্না",
    togetherEm: "পান্দম অমত্তা ওইনা।",
    loginSubtitle: "লোগিন তৌবীয়ু।",
    signupSubtitle: "রেজিস্টার তৌবীয়ু।",
    signInTab: "লোগিন",
    createAccountTab: "রেজিস্টার",
    continueAs: "ওইরগা চত্থবীয়ু",
    createAs: "একাউন্ট শেম্মু",
    rolePatient: "নাজবা",
    rolePatientSub: "হাউবা মীওই",
    roleCaregiver: "যেন্দবা",
    roleCaregiverSub: "ইমুংগী মীওই",
    roleClinician: "ডাক্তার",
    roleClinicianSub: "বিশেষজ্ঞ",
    emailLabel: "ইমেল",
    nameLabel: "মিং",
    passwordLabel: "পাসৱৰ্দ",
    forgotPass: "পাসৱৰ্দ নাইবা?",
    emailPlaceholder: "you@example.com",
    namePlaceholder: "প্রিয়া দেবী",
    passPlaceholder: "মপান্দা লৈবা",
    termsText: "য়াবা পীরি।",
    loginBtn: "মখা তৌবা",
    signupBtn: "শেমগৎপা",
    demoBtn: "ডেমো উবা",
    privacyFooter: "হিংবা মফম।",
    copyright: "© ২০২৬ এআই মেমোরী কেয়ার",
    footerLinks: "মতেং · ঙাকথোকপা",
    verifyTitle: "চেক তৌবা",
    verifyHeader: "সেফ তৌবা",
    verifyHeaderEm: "একাউন্ট।",
    verifySub: "ওটিপি ইশিনবীয়ু",
    verifyBtn: "ওটিপি চেক তৌবা",
    resendText: "ওটিপি ফংদ্রে?",
    resendBtn: "অমুক হন্দোকপা",
    verifying: "চেক তৌরি...",
    creating: "শেম্লি...",
    authenticating: "যাচাই তৌরি...",
    patientProfile: "প্রফাইল",
    managePrefs: "কনফিগার তৌবা",
    logout: "লগ আউট",
    saveChanges: "হেনগৎহনবা",
    profilePhoto: "ফটো",
    imageConstraint: "JPG বা PNG",
    fullName: "মিং কুমার",
    dob: "পোকপা কুমমৈ",
    location: "মফম",
    emergencyContact: "জরুরী তেবা",
    memoryVaultTitle: "নিংশিংবা মফম",
    memoryVaultSub: "পুন্সি",
    addMemoryBtn: "স্মৃতি হাপ্পা",
    aiCompanionTitle: "এআই মরূপ",
    aiCompanionSub: "মরম চাবা থবক",
    talkCompanion: "ৱা হায়নবীয়ু",
    companionSubText: "নিয়ু",
    seeWhatsNext: "মখা তৌবা",
    calmPlan: "থৌরাং",
    todaysMoments: "ঙসিগী মতম",
    beginTogether: "সবম",
    watchReels: "রিল উবা",
    howFeeling: "ফিভম করমব্রা?",
    feelingSub: "হরাওবা",
    littleWindows: "খিৰিকী",
    openVault: "হৌদোকপা",
    exit: "থোরকপা",
    previous: "মাঙদা",
    nextMoment: "মখা তৌবা",
    todaysLastMoment: "অরোইবা",
    thatsAll: "লোই্রে",
    exploreMoments: "উবা",
    backHome: "হোম",
    goodMorning: "নুংথিল খরেরে",
    goodEvening: "নুংথিল কুজিন্নবা",
    goodAfternoon: "নুংথিল",
    interfaceLanguage: "লোন",
    activePatient: "নাজবা",
    selectContext: "বাছিন্নবীয়ু",
    todayOverview: "ঙসি",
    gentleCheckIn: "চেক তৌবা",
    recentActivity: "থবক",
    smallStory: "ৱারি",
    over14Days: "নিবগী মতম",
    usefulPatterns: "মওং",
    viewFullProgress: "প্রোগ্রেস উবা",
    thoughtfulObservation: "মীৎয়েং",
    recentMemoriesHeader: "নিংশিংবা",
    momentsConnect: "ময়োল",
    nextUpHeader: "মখা তৌবা",
    manageAllReminders: "মীৎয়েং থমবা",
    oneThoughtfulStep: "থবক অম",
    addMemoryCardTitle: "ফটো হাপ্পা",
    cognitiveProgressTitle: "প্রোগ্রেস",
    interactiveTracking: "ট্র্যাকিং",
    memoryActivity: "থবক",
    responseTime: "মতম",
    noteOnTracking: "নোট",
    scheduleNewTask: "তাস্ক",
    taskName: "মিং",
    dateTime: "মতম",
    instructions: "ৱাথোক",
    addToSchedule: "হাপ্পা",
    allScheduledReminders: "সবম",
    simulateFamilyMsg: "ইমুংগী পাউজেল",
    simulateSub: "ডেমো",
    sender: "থোকপা",
    messageLabel: "পাউজেল",
    sendBtn: "থোকপা",
    familyHubFeed: "ফিড",
    readAloud: "পাধোকপা",
    caregiverClinicalNotes: "নোট",
    saveNote: "থমহৌবা",
    patientPreferences: "প্রিফারেন্স",
    pushNotifications: "নটিফিকেসন",
    highContrastMode: "মোদ",
    memoryConstellation: "কনস্টেলেসন",
    caregiverProfile: "প্রফাইল",
    caregiverPrefs: "কনফিগার"
  },
  lus: { // Mizo
    tagline: "Duat taka enkawlna",
    heroTitle1: "Hriat rengna hi",
    heroTitle2: "kan kîr leh theihna hmun a ni.",
    heroDesc: "AI hian chhungkua leh enkawlna tura mi thiamte a pui thin.",
    regionNote: "India hmar-chhak lama enkawlna atan siam.",
    privateBadge: "Hmingthup leh venhim",
    welcomeBack: "Kan lo lawm a che",
    beginSpace: "I enkawlna hmun tan rawh",
    seeYouAgain: "Hmuh leh che a nuam e",
    togetherTitle: "Hmasawnna",
    togetherEm: "ruahmanna.",
    loginSubtitle: "I hriat rengna hmunah lut rawh.",
    signupSubtitle: "Chhungkaw tan hmun ruak siam rawh.",
    signInTab: "Luhna",
    createAccountTab: "Account siamna",
    continueAs: "Hman zia",
    createAs: "Account siam dan",
    rolePatient: "Damlo / Hmanraw",
    rolePatientSub: "Tar zual",
    roleCaregiver: "Enkawltu",
    roleCaregiverSub: "Chhungkua",
    roleClinician: "Doctor / Thiam",
    roleClinicianSub: "Hriselna lam mi",
    emailLabel: "Email address",
    nameLabel: "I hming",
    passwordLabel: "Password",
    forgotPass: "Password i theihnghilh em?",
    emailPlaceholder: "you@example.com",
    namePlaceholder: "Priya Devi",
    passPlaceholder: "A tlem berah 6 letters",
    termsText: "Terms ka pawm a, damdawi lam thiam rawn hmasak tur a ni tih ka hria.",
    loginBtn: "Kal zel rawh",
    signupBtn: "Account siam rawh",
    demoBtn: "En hmasa rawh",
    privacyFooter: "I thu leh hla a him reng ang.",
    copyright: "© 2026 AI Memory Care",
    footerLinks: "Puihna · Thuruk",
    verifyTitle: "Tichiang rawh",
    verifyHeader: "I account",
    verifyHeaderEm: "venhim rawh.",
    verifySub: "OTP thawn hi chhut lut rawh",
    verifyBtn: "OTP Check rawh",
    resendText: "Code i dawng lo em?",
    resendBtn: "Thawn nawn leh rawh",
    verifying: "En dik a ni e...",
    creating: "Siam mek a ni...",
    authenticating: "Luh mek a ni...",
    patientProfile: "Patient Profile",
    managePrefs: "Duhthlan dan siamrem rawh",
    logout: "Chhuak rawh",
    saveChanges: "Vawng tha rawh",
    profilePhoto: "Profile Thlalak",
    imageConstraint: "JPG / PNG, max 2MB",
    fullName: "Hming pum",
    dob: "Pian ni",
    location: "Hmun",
    emergencyContact: "Biak pawp na",
    memoryVaultTitle: "Hriat rengna hmun",
    memoryVaultSub: "Nunhlui ngaihtuahna",
    addMemoryBtn: "Thlalak belh rawh",
    aiCompanionTitle: "AI Thian",
    aiCompanionSub: "Hriat rengna atan",
    talkCompanion: "Biak rawh",
    companionSubText: "Ngaihthlak tura awm",
    seeWhatsNext: "A hnuai zel en rawh",
    calmPlan: "Ni tina ruahmanna",
    todaysMoments: "Vawiin hun",
    beginTogether: "Tan dun rawh u",
    watchReels: "Reel en rawh",
    howFeeling: "I awmdan eng nge?",
    feelingSub: "Zawi zawiin",
    littleWindows: "Nunhlui kawngkhar",
    openVault: "Hawng rawh",
    exit: "Chhuahna",
    previous: "Hmasa",
    nextMoment: "A lehpek",
    todaysLastMoment: "Vawiin a tawpna",
    thatsAll: "A tawk e",
    exploreMoments: "En zo ta",
    backHome: "Inah let rawh",
    goodMorning: "Zing chibai",
    goodEvening: "Tlai chibai",
    goodAfternoon: "Chawhnu chibai",
    interfaceLanguage: "Hman lai tawng / Tawng",
    activePatient: "Damlo hmanlai",
    selectContext: "Thlang rawh",
    todayOverview: "Vawiin",
    gentleCheckIn: "Enfiahna",
    recentActivity: "Hna thawh",
    smallStory: "Thawnthu tawi",
    over14Days: "Kar 2 kal ta",
    usefulPatterns: "Thil chin thin",
    viewFullProgress: "Hmasawnna en rawh",
    thoughtfulObservation: "Ngaihtuahna",
    recentMemoriesHeader: "Hriat rengna thar",
    momentsConnect: "Inzawmna",
    nextUpHeader: "A lehpek tur",
    manageAllReminders: "Hriattirna khawih rawh",
    oneThoughtfulStep: "Kallian na",
    addMemoryCardTitle: "Thlalak thar dah rawh",
    cognitiveProgressTitle: "Hmasawnna chin",
    interactiveTracking: "Enfiahna",
    memoryActivity: "Hriat rengna hna",
    responseTime: "Chhanna hun",
    noteOnTracking: "Thuziak",
    scheduleNewTask: "Hna thar ruahman rawh",
    taskName: "Hna hming",
    dateTime: "Hun leh ni",
    instructions: "Hriat tur",
    addToSchedule: "Dah tel rawh",
    allScheduledReminders: "Hriattirna zawng zawng",
    simulateFamilyMsg: "Chhungkaw thuchah",
    simulateSub: "Entirna",
    sender: "Tawn tu",
    messageLabel: "Thuchah",
    sendBtn: "Thawn rawh",
    familyHubFeed: "Chhungkaw thuchah na",
    readAloud: "Chhiar chhuak rawh",
    caregiverClinicalNotes: "Enkawltu ziak",
    saveNote: "Vawng tha rawh",
    patientPreferences: "Duhthlan na",
    pushNotifications: "Hriattirna",
    highContrastMode: "Langchiar",
    memoryConstellation: "Hriat rengna intawnkhawm",
    caregiverProfile: "Enkawltu hming",
    caregiverPrefs: "Duh dan"
  },
  kha: { // Khasi
    tagline: "Ka jingpeit kaba jem",
    heroTitle1: "Ka jingkynmaw",
    heroTitle2: "ka dei ka jaka sha ngi phai biang.",
    heroDesc: "Ka AI ka iarap ia ki longing ban sumar bha.",
    regionNote: "Pynkhreh na ka bynta ka thain shatei lam mihngi.",
    privateBadge: "Kabariei bad kaba shaniah",
    welcomeBack: "Khublei basiew",
    beginSpace: "Sdang ia ka jaka sumar",
    seeYouAgain: "Iohi biang ia phi",
    togetherTitle: "Ka jingiatylli",
    togetherEm: "lang.",
    loginSubtitle: "rung sha ka jaka jingkynmaw.",
    signupSubtitle: "Thaw jaka kaba kyrpang.",
    signInTab: "Rung",
    createAccountTab: "Thaw Account",
    continueAs: "Treikam kum",
    createAs: "Thaw account kum",
    rolePatient: "Nongpang",
    rolePatientSub: "Nongpyndonkam",
    roleCaregiver: "Nongsumar",
    roleCaregiverSub: "Para iing",
    roleClinician: "Doktor",
    roleClinicianSub: "Nongtrei",
    emailLabel: "Email address",
    nameLabel: "Kyrteng",
    passwordLabel: "Password",
    forgotPass: "Klet ia ka password?",
    emailPlaceholder: "you@example.com",
    namePlaceholder: "Priya Devi",
    passPlaceholder: "Kloi 6 kyntien",
    termsText: "Nga pdiang ia ki kyndon sumar.",
    loginBtn: "Pbteng sha AI",
    signupBtn: "Thaw ia la ka jaka",
    demoBtn: "peit ia ka demo",
    privacyFooter: "Ka jingtip jong phi ka shaniah.",
    copyright: "© 2026 AI Memory Care",
    footerLinks: "Iarap · Kabariei",
    verifyTitle: "Pynshisha",
    verifyHeader: "Pynkhlain",
    verifyHeaderEm: "ia ka account.",
    verifySub: "isdan ia ka OTP",
    verifyBtn: "Pynshisha OTP",
    resendText: "ymioh ia ka code?",
    resendBtn: "phah biang OTP",
    verifying: "pynshisha...",
    creating: "thaw...",
    authenticating: "rung...",
    patientProfile: "Profile",
    managePrefs: "pynbeit",
    logout: "Ngiuh shabar",
    saveChanges: "pynskhem",
    profilePhoto: "Photo",
    imageConstraint: "JPG/PNG",
    fullName: "Kyrteng baroh",
    dob: "Sngi kha",
    location: "Jaka",
    emergencyContact: "Nongïarap",
    memoryVaultTitle: "Jaka kynmaw",
    memoryVaultSub: "Ka jingim",
    addMemoryBtn: "Thep kynmaw",
    aiCompanionTitle: "AI Paralok",
    aiCompanionSub: "Kumno sngew",
    talkCompanion: "Iakren",
    companionSubText: "Sngap",
    seeWhatsNext: "Peit nangne",
    calmPlan: "Plan",
    todaysMoments: "Mynta ka sngi",
    beginTogether: "Sdang lang",
    watchReels: "Peit reels",
    howFeeling: "Kumno sngew?",
    feelingSub: "Kloi",
    littleWindows: "Jingshai",
    openVault: "Pynap",
    exit: "Khang",
    previous: "Ba mynshu",
    nextMoment: "Ba bud",
    todaysLastMoment: "Kaba khatduh",
    thatsAll: "La dep",
    exploreMoments: "Peit baroh",
    backHome: "Phai iing",
    goodMorning: "Khublei sngi",
    goodEvening: "Khublei janmiet",
    goodAfternoon: "Khublei sngi",
    interfaceLanguage: "Ktien",
    activePatient: "Nongpang",
    selectContext: "jied",
    todayOverview: "Mynta",
    gentleCheckIn: "Peit bniah",
    recentActivity: "Kam",
    smallStory: "Khana",
    over14Days: "Ar taiew",
    usefulPatterns: "Dustur",
    viewFullProgress: "Peit baroh",
    thoughtfulObservation: "Jingpyrkhat",
    recentMemoriesHeader: "Kynmaw thymmai",
    momentsConnect: "Iadei",
    nextUpHeader: "Ba bud",
    manageAllReminders: "Pynbeit",
    oneThoughtfulStep: "Kiat",
    addMemoryCardTitle: "Thep dur",
    cognitiveProgressTitle: "Progress",
    interactiveTracking: "Peit",
    memoryActivity: "Kam kynmaw",
    responseTime: "Por",
    noteOnTracking: "Note",
    scheduleNewTask: "Thaw kam",
    taskName: "Kyrteng",
    dateTime: "Por bad sngi",
    instructions: "Hikai",
    addToSchedule: "Thep",
    allScheduledReminders: "Baroh",
    simulateFamilyMsg: "Khubor iing",
    simulateSub: "Demo",
    sender: "Nongphah",
    messageLabel: "Khubor",
    sendBtn: "Phah",
    familyHubFeed: "Feed",
    readAloud: "Pule",
    caregiverClinicalNotes: "Note sumar",
    saveNote: "Pynskhem",
    patientPreferences: "Jied",
    pushNotifications: "Notification",
    highContrastMode: "Mode",
    memoryConstellation: "Constellation",
    caregiverProfile: "Profile",
    caregiverPrefs: "Pynbeit"
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => {
    return localStorage.getItem('wecove_app_lang') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('wecove_app_lang', lang);
  }, [lang]);

  const t = (key) => {
    return translations[lang]?.[key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);